data:
  file_path: "data/model_input.csv"
  target_col: "spread_SDAC_IDA1_PL"
  leakage_cols:
    - "spread_SDAC_IDA1_PL"
    - "IDA1_DE"
    - "IDA1_PL"
    - "IDA1_SK"
    - "IDA2_DE"
    - "IDA2_PL"
    - "IDA2_SK"
    - "IDA3_DE"
    - "IDA3_PL"
    - "IDA3_SK"

cv:
  train_days: 180
  meta_train_days: 60
  test_days: 30
  purge_days: 7
  n_splits: 4

model:
  n_estimators: 200
  max_depth: 8
  learning_rate: 0.0736
  subsample: 0.6604
  colsample_bytree: 0.8
  random_state: 42

meta_model:
  n_estimators: 150
  max_depth: 4
  learning_rate: 0.0273
  random_state: 42
  confidence_threshold: 0.5041

mlflow:
  experiment_name: "Day_Ahead_Intraday_Spread"
  run_name: "xgboost_final_tuned"
