data:
  file_path: "data/model_input.csv"
  target_col: "spread_SDAC_IDA1_PL"
  leakage_cols:
    - "spread_SDAC_IDA1_PL"
    - "IDA1_DE"
    - "IDA1_PL"
    - "IDA1_SK"
    - "IDA2_DE"
    - "IDA2_PL"
    - "IDA2_SK"
    - "IDA3_DE"
    - "IDA3_PL"
    - "IDA3_SK"

cv:
  train_days: 180
  meta_train_days: 60 # 'the manager' gets the last 2 months of the train set to learn 'the analyst's' mistakes
  test_days: 30
  purge_days: 7
  n_splits: 4

model:
  n_estimators: 200
  max_depth: 7
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

meta_model:
  n_estimators: 100
  max_depth: 3 # keep the manager shallow so it doesn't overthink
  learning_rate: 0.05
  random_state: 42

mlflow:
  experiment_name: "Day_Ahead_Intraday_Spread"
  run_name: "xgboost_meta_labeling"
